import JSZip from "jszip";

export async function downloadProjectZip(
  files: Record<string, string>,
  projectName = "grimoire-site"
) {
  const zip = new JSZip();
  for (const [path, content] of Object.entries(files)) {
    zip.file(path.replace(/^\/+/, ""), content);
  }
  if (!files["README.md"]) {
    zip.file(
      "README.md",
      `# ${projectName}\n\nGenerated by [Grimoire](https://grimoire.app).\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`
    );
  }
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${projectName.replace(/\s+/g, "-").toLowerCase()}.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function downloadSingleFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
